apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rs
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: wesleywillians/nginx-fullcycle:latest
        ports:
        - containerPort:  80
   